#!/bin/bash

source $(dirname $0)/panel_colors

EMAIL=`cat ~/documents/email.txt`

ICON="^i($PANEL_ICON_DIR/mail.xbm)"

if [[ $EMAIL = "0" ]]; then
	EML_TEXT="no new email"
else
	if [[ $EMAIL = "1" ]]; then
		EML_TEXT="$EMAIL new email"
	else
		EML_TEXT="$EMAIL new emails"
	fi
fi


echo "^fg($PANEL_COLOR_ICON)$ICON ^fg($PANEL_COLOR_TEXT)$EML_TEXT"
