#!/bin/bash

source $(dirname $0)/panel_colors

CURRENT=`mpc current`

if [ "$CURRENT" = "" ]; then
    echo "^fg($PANEL_COLOR_ICON)^i($PANEL_ICON_DIR/phones.xbm) mpd ^fg($PANEL_COLOR_TEXT)stopped"
else
    echo "^fg($PANEL_COLOR_ICON)^i($PANEL_ICON_DIR/phones.xbm)^fg($PANEL_COLOR_TEXT) `mpc current | awk '{split($0,a," - "); print a[1]" ^fg('$PANEL_COLOR_ICON')>^fg('$PANEL_COLOR_TEXT') "a[2]}'`"
fi
