#! /bin/sh

source $(dirname $0)/panel_colors

while true ; do
    echo "S $(applet_email)  $(applet_upd)  $(applet_db)  $(applet_wifi)  $(applet_bt)  $(applet_bat)  $(applet_vol)  ^fg($PANEL_COLOR_ICON)^i($PANEL_ICON_DIR/cal.xbm) ^fg($PANEL_COLOR_TEXT)$(date +"%a %d %b")  ^fg($PANEL_COLOR_ICON)^i($PANEL_ICON_DIR/clock.xbm) ^fg($PANEL_COLOR_TEXT)$(date +"%H:%M")"
    sleep 5
done
